# Site settings
title: 马銮湾1号
SEOTitle: 马銮湾1号| ONE XIAMEN BAY
header-img: img/home-bg.jpg
email: info@one.wenew.uk
description: "这里是 @马銮湾1号 ONE XIAMEN BAY 的专属网站，与你一起共建美好的小区 | 智慧小区，和谐生活。"
keyword: "马銮湾1号, ONE XIAMEN BAY, 乐活岛, 马銮湾新城, 海沧新城, 中心岛, 南岛"
url: "https://one.wenew.uk" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
link_name:  wepro-uk
you_username:  wepro-uk
# weibo_username: xmcmj5
# zhihu_username: wepro-uk
# github_username:  wepro-uk
# twitter_username: jemmy_cn
# facebook_username: jemmy.cn
# linkedin_username:  mingjie-chen
# jianshu_username: b663ec36410e
email_address: info@one.wenew.uk
# 139_username:  wepro
# yun_username:  wepro
# pan_username:  wepro
# zspace_username:  wepro
# lexar_username:  wepro

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: wepro


# Netease settings
netease_comment: false

# Analytics settings
#Baidu Analytics
ba_track_id: 5fe3ef601ea06188fcd208848014b8c6

# Google Analytics
ga_track_id: 'G-ST9558N61S' # Format: UA-xxxxxx-xx
ga_domain: one.wepro.uk

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "共建和谐社区，需要每一位业主 <br> Head Team @ 马銮湾1号"
sidebar-avatar: https://github.com/wepro-uk.png # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "小区系统", href: "https://fwzj-pm.17bbw.com/" },
    { title: "企业微信", href: "https://work.weixin.qq.com/" },
    { title: "微信公众号", href: "https://mp.weixin.qq.com/" },
  ]
